name: Build & Test

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Build
        run: xcodebuild -scheme MathsAr build
      - name: Run tests
        run: xcodebuild clean test -project MAthsAR.xcodeproj -scheme "MathsAr" -destination "name=iPhone 11,OS=13.2.2"
