name: Build & Test

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set version
        run: swift package tools-version --set-current
      - name: Run Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
