name: Swift

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: xcodebuild -scheme "MathsAR" -allowProvisioningUpdates build
      - name: Run tests
        run: xcodebuild clean test -project MathsAR.xcodeproj -scheme "MathsAR" -destination "name=iPhone X,OS=13.1"
